version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - dockerslave
    restart: always
  dockerslave:
    container_name: JenkinsDockerSlave_temp
    build:
      context: .
      dockerfile: JenkinsSlave.Dockerfile
    image: jenkinsdockerslave:latest
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    restart: always
volumes:
  jenkins_home:
